import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "@/app/providers"

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({

  children,

}: {

  children: React.ReactNode

}) {

  return (

    <html lang="en">

      <body className='min-w-screen min-h-screen h-full bg-[#EFF0F3] overflow-x-hidden'>

        <Providers>

          {children}

        </Providers>

      </body>

    </html>

  )

}
